#  阿里短信
sms:
  accessKeyID: LTAI4Fv9NcquxZfjz8YSCNxW
  accessKeySecret: 8KX4y9os2A4fBMGo2Hr7cmb6NTmQvB
  signName: 陌路逢
  verifyCodeTemplate: SMS_179291267

# 邮箱服务器地址
spring:
  mail:
    host: smtp.qq.com
    username: 75746540@qq.com
    password: eejzqrctiwascaef
    default-encoding: UTF-8
# Spring Security
  security:
    user:
      name: user
      password: 123
      roles: admin
